version: '3.8'

services:
  discord-bot:
    build: .
    container_name: dsb-discord-bot
    environment:
      - KEY_DISCORD=${KEY_DISCORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: python main.py
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
