[project]
name = "dsb-bot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "discord.py",
    "colorlog",
    "python-dotenv",
    "aiohttp",
    "rule34py",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["dsb-bot*"]
exclude = ["logs*", "data*", "cogs*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
